[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sciscraper"
description = " A bulk academic PDF extractor program, designed specifically for papers about behavioral science and design."
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.8"
version = "1.0.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Academics",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10"
]
authors = [
    { name="John Fallot", email="john.fallot@gmail.com" },
]
dependencies = [
    "google>=3.0.0",
    "memory_profiler>=0.61.0",
    "pandas>=1.5.2",
    "pdfplumber>=0.7.6",
    "requests>=2.28.1",
    "feedparser>=6.0.10",
    "selectolax>=0.3.11",
    "snakeviz>=2.1.1",
    "tqdm>=4.64.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.10.0",
    "mypy>=0.991",
    "flake8>=6.0.0",
    "tox>=4.0.9",
    "requests-mock>=1.9.3",
]

[project.scripts]
sciscraper = "main:main"

[project.urls]
repository = "https://github.com/Pathos315/sciscraper"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
sciscraper = [
    "py.typed",
]

[tool.setuptools.exclude-package-data]
sciscraper = [
    ".env",
    ".logs/**",
    ".tox/**",
    ".coverage",
    ".venv/**",
    "**/sciscraper.egg-info/**",
    "**/bin/**",
    "**/__pycache__/**",
    "exports/**",
    ".vscode/**",
    "**/lib/**",
]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report term-missing -v"
pythonpath = "."
testpaths = ".test"

[tool.mypy]
mypy_path = "src"
enable_error_code = [
    "truthy-bool",
    "truthy-function",
    "redundant-expr"
]
disable_error_code = [
    "import",
    "no-untyped-def",
    "override",
    "assignment",
    "func-returns-value",
]
show_traceback = true
show_error_context = true
show_column_numbers = true
strict_equality = true
warn_redundant_casts = true
disallow_untyped_calls = true
warn_unreachable = true
