[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sciscraper"
description = " A bulk academic PDF extractor program, designed specifically for papers about behavioral science and design."
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10"
version = "0.5.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Academics",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10"
]
authors = [
    { name="John Fallot", email="john.fallot@gmail.com" },
]
dependencies = [
    "certifi>=2022.9.24",
    "cffi>=1.15.1",
    "charset-normalizer>=2.1.1",
    "cryptography>=38.0.4",
    "Cython>=0.29.32",
    "idna>=3.4",
    "numpy>=1.23.5",
    "pandas>=1.5.2",
    "pdfminer.six>=20221105",
    "pdfplumber>=0.7.6",
    "Pillow>=9.3.0",
    "pycparser>=2.21",
    "python-dateutil>=2.8.2",
    "python-dotenv>=0.21.0",
    "pytz>=2022.6",
    "requests>=2.28.1",
    "selectolax>=0.3.11",
    "six>=1.16.0",
    "snakeviz>=2.1.1",
    "tornado>=6.2",
    "tqdm>=4.64.1",
    "urllib3>=1.26.13",
    "Wand>=0.6.10"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.10.0",
    "mypy>=0.991",
    "flake8>=6.0.0",
    "tox>=4.0.9",
    "responses>=0.22.0",
]

[project.scripts]
sciscraper = "main:main"

[project.urls]
repository = "https://github.com/Pathos315/sciscraper"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
sciscraper = [
    "py.typed",
]

[tool.setuptools.exclude-package-data]
sciscraper = [
    ".env",
    ".logs/**",
    ".tox/**",
    ".coverage",
    ".venv/**",
    "**/sciscraper.egg-info/**",
    "**/bin/**",
    "**/__pycache__/**",
    "exports/**",
    ".vscode/**",
    "**/lib/**",
]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report term-missing -v"
testpaths = [
    "test",
]

[tool.mypy]
mypy_path = "src"
enable_error_code = [
    "truthy-bool",
    "truthy-function",
    "redundant-expr"
]
disable_error_code = [
    "import",
    "no-untyped-def",
    "override",
    "assignment"
]
show_traceback = true
show_error_context = true
show_column_numbers = true
strict_equality = true
warn_redundant_casts = true
disallow_untyped_calls = true
warn_unreachable = true
