[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sciscraper"
version = "0.5.0"
authors = [
    { name="John Fallot", email="john.fallot@gmail.com" },
]
description = " A bulk academic PDF extractor program, designed specifically for papers about behavioral science and design."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10"
]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report term-missing -v"
testpaths = [
    "test",
]

[tool.mypy]
mypy_path = "src"
enable_error_code = [
    "truthy-bool",
    "truthy-function",
    "redundant-expr"
]
disable_error_code = [
    "import",
    "no-untyped-def",
    "override",
    "assignment"
]
show_traceback = true
show_error_context = true
show_column_numbers = true
strict_equality = true
warn_redundant_casts = true
disallow_untyped_calls = true
warn_unreachable = true
